services:
  bitcoind:
    image: fedimint/mutinynet-bitcoind:master
    command: --rpcuser=bitcoin --rpcpassword=bitcoin -zmqpubrawblock=tcp://[::]:48332 -zmqpubrawtx=tcp://[::]:48333
    ports:
      - 0.0.0.0:38333:38333
      - 0.0.0.0:38332:38332
    volumes:
      - bitcoin_datadir:/root/.bitcoin
    networks:
      - dev-net 
    restart: always
    platform: linux/amd64

  lightningd:
    image: elementsproject/lightningd:v24.08.1
    volumes:
      - lightningd_datadir:/root/.lightning
      - bitcoin_datadir:/root/.bitcoin
      - ${PWD}/cln-config:/root/.lightning/config
      - ./plugin-binaries:/root/.lightning/plugins
    environment:
      - MINT_URL=https://mutinynet.nutmix.cash
      - TARGET_CHANNEL_SIZE_SAT=1000000
    networks:
      - dev-net 
    platform: linux/amd64
    command: --network=signet

  # rtl:
  #   image: shahanafarooqui/rtl:v0.15.2
  #   networks:
  #     - dev-net
  #   ports:
  #     - 0.0.0.0:80:80
  #     - 0.0.0.0:443:443


volumes:
  bitcoin_datadir:
    driver: local
  lightningd_datadir:
    driver: local

networks:
  dev-net:
    driver: bridge 